name: CoinWallet
version: '1.0.1'
main: me.hboj.CoinWallet
api-version: "1.21"
softdepend: [Vault]
commands:
  wallet:
    description: Open wallets and access wallet subcommands
    usage: /wallet [open|balance|bal|top|eco]
permissions:
  coinwallet.wallet:
    description: Allows players to open their own wallet
    default: true
  coinwallet.walletbal:
    description: Allows players to check their balance
    default: true
  coinwallet.walletbal-others:
    description: Allows checking other players' balance
    default: op
  coinwallet.wallet-others:
    description: Allows opening other players' wallets (Admin View)
    default: op
  coinwallet.wallettop:
    description: Allows viewing the leaderboard
    default: true
  coinwallet.eco:
    description: Allows using coinwallet eco give/take
    default: op


